### PR TITLE
Fixes bugs with TSCTableInputTextViewViewCell

### PR DESCRIPTION
**Pull request by simonmitchell**

### CODE REVIEW

**Comment by MattCheetham** [comment]
Curious how this will affect other apps that use input rows. Things like emergency sign up. Family safe etc.

Trying to figure out if having it default to this behaviour is correct or not. My gut says it will probably be fine but will probably need to pull this on a few apps and see how it affects them. Which app did you develop this on?

**Comment by simonmitchell** [comment]
Developed on ARC Pet First Aid. The problem was the tableInputViewCellDidFinish method was being called multiple times (3 I think) once by the shouldReturn method, and another couple of times when the next input cell was selected by TSCTableViewController which was resulting in cells being skipped over when the user hit the next button on the keyboard :) 

This hasn't added any extra functionality, simply fixed that already existing behaviour. Emergency sign up and Family Safe shouldn't be affected as I think they're all not using TSCTableInputTextFieldRow, but I will have a check!

**Comment by MattCheetham** [comment]
Cool. Yeah that description is helpful. I understand now what's changed a lot better haha.

Let me know once you've checked on those apps and then I'm happy for it to be merged.

**Comment by simonmitchell** [comment]
Yeah my bad, perhaps should have explained better in the first place! :P 

Checked on ARC Emergency in the "Make a Plan" (The only other place I had us using TSCTableInputTextFieldRow locally) and it still works fine :)

**Pull request merged**
