### PR TITLE
Feature/data did set

### PR DESCRIPTION
**Pull request by BenShutt**
When `reloadData()` is not desired after setting `data` subclasses may set `reloadDataOnDataDidSet = false`.
Subclasses should be responsible for their own reloading in this case. 

## Motivation and Context
Fix issue with a search row in an app referencing this framework.

## How Has This Been Tested?
In the app referencing this framework.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by BenShutt** [comment]
An example here would be
```swift
// Get `IndexSet` to delete and insert
let indexSetToDelete = toDeleteIndexSet()
self.data = sections
let indexSetToInsert = toInsertIndexSet()

// Execute `tableView` updates
tableView.beginUpdates()
tableView.deleteSections(indexSetToDelete, with: .fade)
tableView.insertSections(indexSetToInsert, with: .fade)
tableView.endUpdates()
```

**Comment by simonmitchell** [comment]
Nice! I actually need this for something I'm working on at the moment in Camrote. My only thought is it may also be nice to get a temporary disabling rather than a toggle (As well?) So you could either:
```
reloadDataOnDataDidSet = false
// Get `IndexSet` to delete and insert
let insetSetToDelete = toDeleteIndexSet()
self.data = sections
let insetSetToInsert = toInsertIndexSet()

// Execute `tableView` updates
tableView.beginUpdates()
tableView.deleteSections(insetSetToDelete, with: .fade)
tableView.insertSections(insetSetToInsert, with: .fade)
tableView.endUpdates()
reloadDataOnDataDidSet = true
```

OR

```
withoutReloading { // Store a separate boolean to `reloadDataOnDataDidSet`
    // Get `IndexSet` to delete and insert
    let insetSetToDelete = toDeleteIndexSet()
    self.data = sections
    let insetSetToInsert = toInsertIndexSet()

    // Execute `tableView` updates
    tableView.beginUpdates()
    tableView.deleteSections(insetSetToDelete, with: .fade)
    tableView.insertSections(insetSetToInsert, with: .fade)
    tableView.endUpdates()
}
```

**Comment by BenShutt** [comment]
@simonmitchell Yeah that does make sense :). I guess it would fundamentally work the same as this, but `reloadDataOnDataDidSet` would become `private` and we make a new public interface for `withoutReloading`

**Review by simonmitchell — APPROVED** [review]
Approving, discussion above can be done at a future date!

**Pull request merged**
